

##################################################################################################
# Billing service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: billing
  labels:
    privacy: Confidential
    app: billing
spec:
  ports:
  - port: 9080
    targetPort: 8088
    name: http
  selector:
    app: billing
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: billing-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing
        version: billing
        privacy: Confidential
    spec:
      containers:
      - name: appd
        image: appdynamicssecuritymodule:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088

---
##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    privacy: Confidential
    app: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: details-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: details
        version: v1
        privacy: Confidential
    spec:
      containers:
      - name: details
        image: istio/examples-bookinfo-details-v1:0.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    privacy: TopSecret
    app: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratings-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
        privacy: TopSecret
    spec:
      containers:
      - name: ratings
        image: istio/examples-bookinfo-ratings-v1:0.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    privacy: Confidential
    app: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
        privacy: Confidential
    spec:
      containers:
      - name: reviews
        image: istio/examples-bookinfo-reviews-v1:0.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v2
        privacy: Confidential
    spec:
      containers:
      - name: reviews
        image: istio/examples-bookinfo-reviews-v2:0.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v3
        privacy: Confidential
    spec:
      containers:
      - name: reviews
        image: istio/examples-bookinfo-reviews-v3:0.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    privacy: Normal
    app: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
        privacy: Normal
    spec:
      containers:
      - name: productpage
        image: billing:cloud
        env:
          - name: ENABLE_BILLING
            value: "true"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  tls:
  - secretName: istio-ingress-certs
  rules:
  - http:
      paths:
      - path: /productpage
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /login
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /logout
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /api/v1/products.*
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /SecurityEventRestService/event/query
        backend:
          serviceName: billing
          servicePort: 9080
      - backend:
          serviceName: billing
          servicePort: 9080
        path: /SecurityEventDemoServlet/execute.*
      - backend:
          serviceName: billing
          servicePort: 9080
        path: /SecurityEventRestService/event/events
      - backend:
          serviceName: billing
          servicePort: 9080
        path: /SecurityEventRestService/event.*
      - backend:
          serviceName: productpage
          servicePort: 9080
        path: /api/speech.*
